RegisterCommand("pos", function()
    local pCoords = GetEntityCoords(slyyCore.pPed)
    local pHeading = GetEntityHeading(slyyCore.pPed)
    slyyCore.events:server("toServerPrint", ("vector3(%s, %s, %s) - %s"):format(pCoords.x, pCoords.y, pCoords.z, pHeading))
end, false)